stalker:
       world: world
#мир в котором необходим выброс
       rand: true
       time: 600
       main_poison: false
       bleeding: false
       poison: 100
       dmg_bleeding: 1

# rand: возможные значения true и false ! если true то время между выбросами рандомное
# если false то время берется из time ! значения в time целые числа! 1 сек = 20 тиков! время указывать в тиках.
# poison - время отравления зомби в тиках.
#dmg_bleeding - урон от кровотечения каждую секунду Пример: dmg_bleeding: 100 
# main_poison: true/false включенно ли отравление при ударе зомби. Вероятность отравления 50%.
# bleeding: true/false включено ли кровотечение при ударе зомби. Вероятность кровотечения 50%.




# Plugin by Failer 
# failerept8@gmail.com
# спасибки сюда:
# R261034216073
# Z221643925630
# Обо всех ошибках писать сюда : failerept8@gmail.com